fragment PageParts on Page {
  __typename
  blocks {
    __typename
    ... on PageBlocksHero {
      background
      headline
      tagline
      actions {
        __typename
        label
        type
        icon {
          __typename
          name
          color
          style
        }
        link
      }
      image {
        __typename
        src
        alt
        videoUrl
      }
    }
    ... on PageBlocksCallout {
      background
      text
      url
    }
    ... on PageBlocksFeatures {
      background
      title
      description
      items {
        __typename
        icon {
          __typename
          name
          color
          style
        }
        title
        text
      }
    }
    ... on PageBlocksStats {
      background
      title
      description
      stats {
        __typename
        stat
        type
      }
    }
    ... on PageBlocksCta {
      title
      description
      actions {
        __typename
        label
        type
        icon {
          __typename
          name
          color
          style
        }
        link
      }
    }
    ... on PageBlocksContent {
      background
      body
    }
    ... on PageBlocksTestimonial {
      background
      title
      description
      testimonials {
        __typename
        quote
        author
        role
        avatar
      }
    }
    ... on PageBlocksVideo {
      background
      color
      url
      autoPlay
      loop
    }
  }
}

fragment PostParts on Post {
  __typename
  title
  heroImg
  excerpt
  author {
    ... on Author {
      __typename
      name
      avatar
    }
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
  }
  date
  _body
}

fragment AuthorParts on Author {
  __typename
  name
  avatar
}

fragment GlobalParts on Global {
  __typename
  header {
    __typename
    icon {
      __typename
      name
      color
      style
    }
    name
    color
    nav {
      __typename
      href
      label
    }
  }
  footer {
    __typename
    social {
      __typename
      icon {
        __typename
        name
        color
        style
      }
      url
    }
  }
  theme {
    __typename
    color
    font
    darkMode
  }
}
