import type { BinKey } from "./bins";

/**
 * The item dictionary behind the bin finder.
 *
 * Compact tuple form to keep it editable:
 *   [name, bin, detail?, "alias|alias|alias"?]
 *
 * Rules applied consistently throughout:
 *   green  — food and garden matter that will break down
 *   blue   — clean, dry, sorted recyclables
 *   red    — multilayered, soiled, mixed or sanitary rejects
 *   yellow — chemicals, medicines, oils, biohazard
 *   black  — anything electrical, plus bulky and construction streams
 */
export type Row =
  | [string, BinKey]
  | [string, BinKey, string]
  | [string, BinKey, string, string];

export type Category = { group: string; rows: Row[] };

export const categories: Category[] = [
  {
    group: "Food & kitchen",
    rows: [
      ["Leftover cooked food", "green", "Drain any liquid first.", "plate scrape|mess food|rice|curry|sambar|dal|idli|dosa|roti|chapati|sabzi|biryani|leftovers"],
      ["Vegetable peel", "green", "", "peel|potato skin|onion skin|carrot"],
      ["Fruit peel", "green", "", "banana peel|orange peel|mango skin|apple core"],
      ["Banana peel", "green"],
      ["Egg shells", "green", "", "egg|eggshell"],
      ["Tea leaves", "green", "", "chai|used tea"],
      ["Tea bag", "green", "Paper bags compost; silk-style mesh bags do not.", "teabag"],
      ["Coffee grounds", "green", "", "coffee|filter coffee|decoction"],
      ["Coconut shell", "green", "The segregation yard sorts these as their own category.", "coconut"],
      ["Coconut husk", "green"],
      ["Bones", "green", "Goes with wet waste to the digester.", "chicken bones|fish bones"],
      ["Fish and meat scraps", "green", "", "meat|fish|chicken waste"],
      ["Stale bread", "green", "", "bread|bun|pav"],
      ["Expired food", "green", "Empty the packet into green; the packet itself goes to red or blue.", "spoiled food|rotten"],
      ["Curd cup", "blue", "Rinse and dry. It is rigid plastic.", "yoghurt cup|dahi cup"],
      ["Milk pouch", "red", "Multilayered. Rinse and keep dry for a Punch the Plastic point if you can.", "milk packet|milk cover|milk sachet"],
      ["Milk carton", "red", "Tetra pak is card bonded to plastic and foil — the yard calls it KD.", "tetra pak|juice carton|buttermilk carton"],
      ["Paper cup", "red", "Lined with plastic, so it cannot be recycled as paper.", "coffee cup|tea cup|disposable cup"],
      ["Paper plate", "red", "Usually plastic-lined, and usually soiled.", "disposable plate"],
      ["Plastic cutlery", "red", "", "spoon|fork|plastic spoon|disposable cutlery"],
      ["Wooden cutlery", "green", "Untreated wood composts.", "wooden spoon|ice cream stick"],
      ["Steel tumbler", "blue", "If it is beyond use. Otherwise keep using it.", "tumbler|steel glass"],
      ["Pressure cooker", "black", "Scrap metal via bulky collection.", "cooker"],
      ["Non-stick pan", "black", "Coated metal — goes to scrap, not blue.", "frying pan|tawa|kadai"],
      ["Aluminium foil", "blue", "Only if clean. Foil with food on it goes to red.", "foil|silver foil"],
      ["Cling film", "red", "", "plastic wrap|cling wrap"],
      ["Butter paper", "red", "", "parchment|baking paper"],
      ["Takeaway container", "blue", "Rinse with plain water and let it dry.", "parcel box|food container|tiffin box"],
      ["Styrofoam container", "red", "", "thermocol box|foam container"],
      ["Pizza box", "red", "The greasy base is a reject; tear off and recycle the clean lid.", "pizza carton"],
      ["Used cooking oil", "yellow", "Collect in a sealed bottle for the oil collection point. Never down the drain.", "oil|frying oil|refined oil"],
      ["Ghee tin", "blue", "Empty and rinse.", "ghee|dalda tin"],
      ["Pickle jar", "blue", "Rinse. Glass jars stay whole.", "jar|achar jar"],
      ["Spice packet", "red", "Multilayered.", "masala packet"],
      ["Sauce sachet", "red", "", "ketchup sachet|sachet"],
      ["Straw", "red", "", "plastic straw|drinking straw"],
      ["Paper straw", "green"],
      ["Chopsticks", "green", "", "chopstick"],
      ["Water bottle (plastic)", "blue", "Rinse, leave the cap on, do not crush.", "pet bottle|bisleri|mineral water"],
      ["Water bottle (steel)", "blue", "Only when it is genuinely finished.", "flask|thermos"],
      ["Soft drink can", "blue", "Empty and rinse.", "coke can|pepsi can|beverage can|aluminium can"],
      ["Glass bottle", "blue", "Rinse and keep whole. Broken glass goes to red.", "beer bottle|soda bottle"],
      ["Juice bottle", "blue", "", "juice"],
      ["Ice cream tub", "blue", "Rinse.", "ice cream"],
      ["Chewing gum", "red", "", "gum|bubblegum"],
      ["Cigarette butt", "red", "The filter is plastic and the whole thing is contaminated.", "cigarette|butt|beedi"],
      ["Matchsticks", "green", "", "matchstick|matchbox"],
      ["Candle stub", "red", "", "candle|wax"],
      ["Salt packet", "red"],
      ["Rice bag (woven)", "blue", "Woven polypropylene sacks are recoverable if clean.", "gunny bag|sack|rice sack"],
      ["Bread packet", "red", "", "bread cover"],
      ["Curd packet", "red", "", "curd sachet"],
      ["Water can (20L)", "blue", "The yard sorts these as their own category.", "bubble top|water jar|20 litre can"],
    ],
  },

  {
    group: "Packaging",
    rows: [
      ["Cardboard box", "blue", "Flatten it and stack it beside the bin, not inside.", "carton|delivery box|amazon box|parcel|corrugated"],
      ["Courier envelope", "red", "Plastic mailers are not recyclable; paper ones are.", "poly mailer|flyer bag|courier bag"],
      ["Bubble wrap", "blue", "Clean single-layer film — keep it dry and bundled.", "bubblewrap"],
      ["Packing foam", "red", "", "foam sheet|eps"],
      ["Thermocol", "red", "", "styrofoam|polystyrene|packing foam"],
      ["Carry bag", "blue", "Clean and dry only. A greasy bag goes to red.", "plastic bag|polythene|cover|shopping bag"],
      ["Cloth bag", "blue", "Reuse it. Worn-out cloth goes to the textile stream.", "jute bag|tote"],
      ["Chip packet", "red", "Multilayered foil — not conventionally recyclable.", "lays|crisps|snack wrapper|chips|kurkure"],
      ["Biscuit packet", "red", "", "cookie packet|parle|marie"],
      ["Chocolate wrapper", "red", "", "candy wrapper|sweet wrapper|toffee"],
      ["Instant noodle packet", "red", "", "maggi|noodles|ramen"],
      ["Shampoo bottle", "blue", "Rinse.", "shampoo|conditioner bottle"],
      ["Detergent bottle", "blue", "Rinse thoroughly.", "detergent|surf|liquid detergent"],
      ["Detergent sachet", "red", "", "shampoo sachet|sachet"],
      ["Toothpaste tube", "red", "Multilayered plastic and aluminium.", "toothpaste"],
      ["Bottle cap", "blue", "Leave it on the bottle.", "cap|lid"],
      ["Blister pack", "red", "Foil bonded to plastic.", "tablet strip|medicine strip"],
      ["Egg tray (paper)", "green", "Moulded pulp composts.", "egg carton"],
      ["Egg tray (plastic)", "blue"],
      ["Tin can", "blue", "Empty and rinse.", "tin|food can|steel can"],
      ["Aerosol can", "yellow", "Pressurised — never crush or bin it.", "spray can|deodorant can"],
      ["Paint tin", "yellow", "", "paint|varnish tin"],
      ["Shoe box", "blue", "", "shoebox"],
      ["Gift wrapping paper", "blue", "Plain paper only; foil and glitter wrap goes to red.", "wrapping paper|gift wrap"],
      ["Glitter wrapping paper", "red"],
      ["Ribbon", "red", "", "gift ribbon"],
      ["Sticky label", "red", "", "label|sticker"],
      ["Strapping tape", "red", "", "packing tape|brown tape"],
      ["Plastic strapping", "red", "", "strap|banding"],
      ["Silica gel sachet", "red", "", "silica|desiccant"],
      ["Blister-packed electronics packaging", "red", "", "clamshell"],
      ["Laminated pouch", "red", "", "stand-up pouch|zip pouch"],
      ["Jute sack", "green", "Natural fibre.", "gunny"],
      ["Wooden crate", "blue", "Offer it to the Engineering Unit for reuse first.", "crate|pallet|wooden box"],
      ["Oil packet", "red", "The yard sorts these separately.", "oil pouch|cooking oil sachet"],
      ["Mica packaging", "red", "The yard's name for low-grade plastic film.", "mica"],
    ],
  },

  {
    group: "Paper & stationery",
    rows: [
      ["Newspaper", "blue", "", "paper|news|raddi"],
      ["Magazine", "blue", "", "journal|periodical"],
      ["Notebook", "blue", "Remove any spiral binding first.", "register|note book|exercise book"],
      ["Textbook", "blue", "If it is still readable, take it to the book bank instead.", "book|course book|reference book"],
      ["Exam script", "blue", "Clean, dry paper is the highest-value thing the campus recycles.", "answer sheet|exam paper|answer script"],
      ["Printout", "blue", "", "printed paper|a4|photocopy|xerox"],
      ["Envelope", "blue", "Window envelopes are fine.", "cover"],
      ["Cardboard file", "blue", "", "file|folder|box file"],
      ["Plastic folder", "red", "PVC — not recoverable.", "pvc folder|sheet protector"],
      ["Sticky notes", "blue", "", "post it|post-it"],
      ["Graph paper", "blue"],
      ["Tracing paper", "red", "Coated, so it contaminates the paper stream.", "butter paper"],
      ["Carbon paper", "red"],
      ["Thermal receipt", "red", "Coated with BPA — keep it out of the paper stream.", "bill|receipt|atm slip"],
      ["Laminated sheet", "red", "", "lamination|laminated notice"],
      ["Poster", "blue", "Paper posters only. Flex and vinyl go to red.", "chart paper"],
      ["Flex banner", "red", "Design banners without the year so they can be reused.", "banner|vinyl|flex"],
      ["Pen", "red", "Mixed plastic and metal — not recoverable.", "ballpoint|biro|gel pen"],
      ["Pencil", "green", "Bare wood composts; plastic-bodied ones go to red.", "wooden pencil"],
      ["Mechanical pencil", "red", "", "clutch pencil"],
      ["Eraser", "red", "", "rubber"],
      ["Sharpener", "blue", "Metal-bodied sharpeners are recoverable.", "pencil sharpener"],
      ["Sharpener blade", "blue", "Wrap it so nobody is cut.", "blade"],
      ["Whiteboard marker", "red", "", "marker pen|board marker"],
      ["Permanent marker", "red", "", "sketch pen|highlighter"],
      ["Correction pen", "red", "", "whitener|white out"],
      ["Glue stick", "red", "", "adhesive|fevistick"],
      ["Glue bottle", "red", "", "fevicol|gum bottle"],
      ["Sticky tape", "red", "", "cellotape|sellotape|scotch tape"],
      ["Stapler pins", "blue", "Recoverable metal.", "staples|pin"],
      ["Paper clips", "blue", "", "clip|binder clip"],
      ["Rubber band", "red", "", "rubberband"],
      ["Ruler (plastic)", "red", "", "scale|plastic scale"],
      ["Ruler (wooden)", "green"],
      ["Compass and divider", "blue", "Metal instruments are recoverable.", "geometry box"],
      ["Spiral binding", "red", "Separate it from the paper block first.", "spiral|comb binding"],
      ["Chart paper", "blue"],
      ["Cardboard tube", "blue", "", "tube|roll core"],
      ["Toner cartridge", "black", "Return it to the supplier under the purchase agreement.", "cartridge|ink cartridge|printer cartridge"],
      ["Ink bottle", "yellow", "", "ink|refill"],
      ["ID card", "red", "", "identity card|access card"],
      ["Visiting card", "blue", "", "business card"],
      ["Diary", "blue", "Remove any leather or plastic cover.", "planner"],
      ["Calendar", "blue", "", "wall calendar"],
      ["Photograph", "red", "Photo paper is coated.", "photo|print"],
      ["Tissue paper", "red", "Used tissue is a reject; unused is paper.", "napkin|serviette"],
      ["Paper bag", "blue", "", "carry bag paper"],
      ["Book cover (plastic)", "red", "", "brown cover"],
    ],
  },

  {
    group: "Electronics & electrical",
    rows: [
      ["Battery", "black", "Never any of the three bins. Take it to an e-waste point.", "cell|aa|aaa|dry cell|button cell"],
      ["Rechargeable battery", "black", "", "li-ion|lithium|nimh"],
      ["Power bank", "black", "", "powerbank"],
      ["Laptop battery", "black", "Never puncture or heat it.", "battery pack"],
      ["UPS battery", "black", "Lead-acid — heavy and hazardous.", "inverter battery|lead acid"],
      ["Phone charger", "black", "", "cable|adapter|charger|usb cable"],
      ["Laptop", "black", "Wipe your data first. If it still works, pass it on rather than scrapping it.", "computer|notebook computer"],
      ["Desktop computer", "black", "", "cpu|pc|tower"],
      ["Monitor", "black", "", "screen|display|crt|lcd"],
      ["Keyboard", "black", "", "keypad"],
      ["Mouse", "black", "", "computer mouse"],
      ["Printer", "black", "", "scanner|photocopier"],
      ["Mobile phone", "black", "Wipe it and remove the battery.", "phone|smartphone|cellphone"],
      ["Earphones", "black", "", "headphones|earbuds|airpods"],
      ["Speaker", "black", "", "bluetooth speaker|woofer"],
      ["Television", "black", "", "tv|led tv"],
      ["Remote control", "black", "Take the batteries out first.", "remote"],
      ["Calculator", "black", "", "scientific calculator"],
      ["Wristwatch", "black", "", "watch|smartwatch"],
      ["Tube light", "black", "Never break it — tubes and CFLs contain mercury.", "tubelight|fluorescent"],
      ["CFL bulb", "black", "", "cfl|compact fluorescent"],
      ["LED bulb", "black", "", "led|light bulb"],
      ["Incandescent bulb", "black", "", "bulb|filament bulb"],
      ["Light fitting", "black", "", "ballast|starter|choke|fixture"],
      ["Extension board", "black", "", "extension cord|power strip|spike guard"],
      ["Plug and socket", "black", "", "plug|socket|switch"],
      ["Electrical wire", "black", "The yard sorts wire as its own category.", "wire|cable|copper wire"],
      ["Circuit board", "black", "", "pcb|motherboard|board"],
      ["Hard drive", "black", "Wipe or destroy the data first.", "hdd|ssd|disk"],
      ["Pen drive", "black", "", "usb drive|flash drive|memory card"],
      ["CD or DVD", "black", "The yard sorts CDs and cassettes as their own category.", "cd|dvd|disc|cassette"],
      ["Router", "black", "", "modem|wifi router"],
      ["Table fan", "black", "", "fan|pedestal fan|ceiling fan"],
      ["Air conditioner", "black", "Refrigerant must be recovered by a technician.", "ac|split ac|window ac"],
      ["Refrigerator", "black", "", "fridge"],
      ["Water heater", "black", "", "geyser|immersion rod"],
      ["Microwave oven", "black", "", "microwave|oven"],
      ["Electric kettle", "black", "", "kettle"],
      ["Induction cooktop", "black", "", "induction stove"],
      ["Mixer grinder", "black", "", "mixie|blender|grinder"],
      ["Rice cooker", "black", "", "cooker electric"],
      ["Iron (clothes)", "black", "", "electric iron|press"],
      ["Hair dryer", "black", "", "hairdryer|straightener"],
      ["Sewing machine", "black", "", "machine"],
      ["Solar panel", "black", "Specialist recovery — do not put it in a skip.", "pv panel"],
      ["Smoke detector", "black", "Some contain a radioactive source; hand it over, never bin it.", "detector|alarm"],
      ["Thermometer (mercury)", "yellow", "Mercury is hazardous — report a breakage immediately.", "mercury thermometer"],
      ["Thermometer (digital)", "black"],
      ["Multimeter", "black", "", "meter|instrument"],
      ["Sensor module", "black", "", "sensor|arduino|raspberry pi"],
      ["Soldering iron", "black", "", "solder iron"],
      ["Solder waste", "yellow", "Lead-bearing.", "solder|flux"],
    ],
  },

  {
    group: "Laboratory & chemicals",
    rows: [
      ["Laboratory solvent", "yellow", "Labelled container, logbook entry, certified consignment. Never a sink.", "acetone|methanol|toluene|benzene|chloroform|solvent"],
      ["Spent acid", "yellow", "Neutralise under your supervisor's protocol and record it.", "acid|hcl|sulphuric|nitric"],
      ["Spent base", "yellow", "", "base|naoh|koh|alkali"],
      ["Buffer solution", "yellow", "", "buffer|phosphate buffer"],
      ["Reaction residue", "yellow", "", "reaction mixture|residue"],
      ["Staining dye", "yellow", "Several are mutagenic — decontaminate before consignment.", "crystal violet|safranin|ethidium bromide|dye|stain"],
      ["Petri dish with culture", "yellow", "Autoclave before it leaves the lab.", "agar|culture plate|biohazard"],
      ["Agar plate", "yellow"],
      ["Bacterial culture", "yellow", "", "culture|microbial"],
      ["Contaminated tissue", "yellow", "", "kimwipe|lab tissue"],
      ["Lab gloves", "yellow", "If they touched a reagent. Gloves that touched nothing are ordinary waste.", "nitrile|latex gloves|gloves"],
      ["Pipette tips", "yellow", "", "microtips|tips"],
      ["Eppendorf tube", "yellow", "", "eppendorf|microcentrifuge tube"],
      ["Filter paper (used)", "yellow", "", "filter paper|whatman"],
      ["Filter paper (unused)", "blue"],
      ["Microtip box (clean)", "blue", "Clean lab plastics are ordinary recycling — sign them separately.", "tip box"],
      ["Reagent bottle (clean)", "blue", "Triple-rinsed and label removed.", "reagent bottle"],
      ["Reagent bottle (residue)", "yellow"],
      ["Broken glassware", "red", "Wrap, label ‘broken glass — sharp’, and use the rigid box.", "broken beaker|broken flask|cracked test tube"],
      ["Test tube", "blue", "Intact and clean.", "tube"],
      ["Beaker", "blue", "Intact and clean.", "glassware"],
      ["Measuring cylinder", "blue"],
      ["Pasteur pipette", "red", "Glass — treat as sharps.", "pipette"],
      ["Syringe", "yellow", "Rigid, puncture-proof sharps box only.", "needle|sharps"],
      ["Scalpel blade", "yellow", "", "blade|surgical blade"],
      ["Microscope slide", "red", "Wrap it — it is glass.", "slide|coverslip"],
      ["Gel (electrophoresis)", "yellow", "", "agarose gel|sds page"],
      ["Silica gel (lab)", "yellow", "", "silica|column silica"],
      ["Chromatography solvent", "yellow", "", "hplc solvent|mobile phase"],
      ["Compressed gas cylinder", "yellow", "Return it to the supplier — never a bin.", "gas cylinder|cylinder"],
      ["Lab coat", "red", "Route through the repair and reuse pool first.", "labcoat|apron"],
      ["Safety goggles", "red", "", "goggles|eye protection"],
      ["Heating mantle", "black", "", "mantle|hot plate"],
      ["Desiccant", "red", "", "drying agent"],
      ["Paraffin wax", "red", "", "wax|parafilm"],
      ["Expired reagent", "yellow", "List surplus on the exchange register before it expires.", "expired chemical|old reagent"],
      ["Oil bath oil", "yellow", "", "silicone oil|bath oil"],
      ["Vacuum pump oil", "yellow", "", "pump oil"],
      ["Contaminated foil", "yellow", "", "lab foil"],
    ],
  },

  {
    group: "Personal care & medical",
    rows: [
      ["Sanitary napkin", "red", "Wrap in opaque paper or a marked bag. Use the dedicated bin where there is one.", "pad|sanitary pad|menstrual pad"],
      ["Tampon", "red", "", "tampon"],
      ["Menstrual cup", "red", "", "cup"],
      ["Diaper", "red", "Wrap securely before disposal.", "nappy|pampers"],
      ["Used tissue", "red", "", "tissue|napkin"],
      ["Cotton buds", "red", "", "earbuds|cotton swab|q-tip"],
      ["Cotton wool", "red", "", "cotton"],
      ["Bandage", "red", "", "band aid|dressing|gauze"],
      ["Face mask", "red", "", "mask|surgical mask|n95"],
      ["Expired medicine", "yellow", "Hold it for the monthly hazardous drive. Never the drain, never a bin.", "tablets|syrup|medicines|drugs|capsules"],
      ["Medicine strip", "red", "Foil bonded to plastic.", "blister|tablet strip"],
      ["Medicine bottle", "blue", "Rinse. If it held a controlled drug, hand it over instead.", "syrup bottle"],
      ["Inhaler", "black", "Pressurised canister — hand it over.", "asthma pump"],
      ["Contact lenses", "red", "Never down the drain.", "lens|contacts"],
      ["Spectacles", "black", "Working spectacles are worth donating.", "glasses|specs"],
      ["Toothbrush", "red", "", "brush"],
      ["Razor", "red", "Wrap the blade.", "shaving razor|blade"],
      ["Comb", "red"],
      ["Soap wrapper", "red", "", "soap cover"],
      ["Soap bar remnant", "green", "", "soap"],
      ["Shampoo sachet", "red"],
      ["Cosmetic container", "blue", "Rinse.", "cream jar|lotion bottle|makeup"],
      ["Nail polish", "yellow", "Solvent-based.", "nail paint|remover"],
      ["Perfume bottle", "blue", "Empty glass. Aerosol versions go to yellow.", "deodorant bottle|scent"],
      ["Deodorant spray", "yellow", "Pressurised.", "deo|aerosol"],
      ["Hand sanitiser bottle", "blue", "Rinse.", "sanitizer"],
      ["Hair", "red", "", "hair strands"],
      ["Nail clippings", "red"],
      ["Sunscreen tube", "red", "", "sunscreen|lotion tube"],
      ["Thermometer cover", "red"],
    ],
  },

  {
    group: "Textiles & footwear",
    rows: [
      ["Old clothes", "red", "Wearable clothing belongs in a donation drive, not a bin.", "clothing|textile|shirt|trousers|kurta|saree"],
      ["Bedsheet", "red", "Worn cotton makes good cleaning cloth first.", "bed sheet|linen"],
      ["Pillow", "red", "", "cushion"],
      ["Pillow cover", "red", "", "pillowcase"],
      ["Blanket", "red", "Donate if usable.", "quilt|razai"],
      ["Curtain", "red", "", "curtains|drape"],
      ["Towel", "red", "", "bath towel"],
      ["Handkerchief", "red", "", "hanky"],
      ["Socks", "red", "", "sock"],
      ["Footwear", "red", "", "shoes|slippers|chappal|sandals|flip flops"],
      ["Sports shoes", "red", "", "sneakers|running shoes"],
      ["Doormat", "red", "", "mat|floor mat"],
      ["Carpet", "black", "Bulky — book a collection.", "rug|durrie"],
      ["Backpack", "red", "Donate if usable.", "bag|rucksack|school bag"],
      ["Umbrella", "black", "Metal frame and fabric — scrap stream.", "umbrella"],
      ["Belt", "red", "", "leather belt"],
      ["Cap or hat", "red", "", "cap|hat"],
      ["Mosquito net", "red", "", "net|window net"],
      ["Cleaning cloth", "red", "", "duster|rag|wiping cloth"],
      ["Mop head", "red", "", "mop"],
      ["Rope", "red", "", "nylon rope|twine"],
      ["Yarn and thread", "red", "", "wool|thread|knitting"],
    ],
  },

  {
    group: "Furniture & bulky",
    rows: [
      ["Mattress", "black", "At semester end, take it to the handover depot rather than the corridor.", "bed|bedding|foam mattress"],
      ["Bed frame", "black", "", "cot|bedstead"],
      ["Chair", "black", "Offer it to the swap shelf first.", "seat|office chair|plastic chair"],
      ["Table", "black", "", "desk|study table"],
      ["Cupboard", "black", "", "almirah|wardrobe|shelf"],
      ["Bookshelf", "black", "", "rack|shelving"],
      ["Sofa", "black", "", "couch|settee"],
      ["Bucket", "blue", "Rigid plastic. If it still holds water, pass it on.", "mug|bucket plastic"],
      ["Plastic drum", "blue", "", "drum|barrel"],
      ["Suitcase", "black", "", "trolley bag|luggage"],
      ["Trunk (metal)", "black", "Scrap metal.", "steel trunk|box"],
      ["Mirror", "red", "Silvered glass is not recyclable. Wrap it.", "looking glass"],
      ["Window glass", "red", "Wrap and label it.", "glass pane|broken window"],
      ["Clothes hanger (plastic)", "red"],
      ["Clothes hanger (metal)", "blue"],
      ["Clothes drying rack", "black", "", "drying stand"],
      ["Mattress protector", "red"],
      ["Study lamp", "black", "", "table lamp|desk lamp"],
      ["Wall clock", "black", "Remove the battery.", "clock"],
      ["Water filter", "black", "", "ro|purifier|aquaguard"],
      ["Cycle", "black", "Working cycles go to the cycle pool; the rest are stripped for parts.", "bicycle|bike"],
      ["Cycle tyre", "red", "Rubber — not recoverable through the usual streams.", "tyre|tube|tire"],
      ["Cycle chain", "blue", "Scrap metal.", "chain"],
      ["Helmet", "red", "", "bike helmet"],
      ["Motorbike battery", "black", "Lead-acid.", "two wheeler battery"],
      ["Engine oil", "yellow", "Hand it to the workshop, never the drain.", "motor oil|used oil|lubricant"],
      ["Car tyre", "black", "Specialist recovery.", "tyre"],
      ["Scrap metal", "blue", "The yard sorts iron, tin and steel separately.", "iron|steel|metal scrap"],
    ],
  },

  {
    group: "Garden & outdoor",
    rows: [
      ["Garden trimmings", "green", "", "leaves|grass|clippings|branches|pruning"],
      ["Fallen leaves", "green", "", "leaf litter|dry leaves"],
      ["Grass clippings", "green"],
      ["Flowers", "green", "Festival flowers compost well.", "floral waste|garland|puja flowers"],
      ["Weeds", "green"],
      ["Soil", "green", "", "mud|earth"],
      ["Plant pot (clay)", "red", "Broken terracotta is inert.", "terracotta pot|earthen pot"],
      ["Plant pot (plastic)", "blue", "", "nursery pot"],
      ["Coir", "green", "", "coco peat|coir pith"],
      ["Compost", "green", "", "manure|vermicompost"],
      ["Wood offcuts", "green", "Untreated wood only. Painted or treated wood goes to black.", "timber|wood"],
      ["Treated wood", "black", "", "plywood|laminate"],
      ["Bamboo", "green", "", "bamboo pole"],
      ["Animal droppings", "green", "", "dung|droppings"],
      ["Garden hose", "red", "", "hose|pipe"],
      ["Watering can", "blue"],
      ["Pesticide container", "yellow", "Triple-rinse and hand over; never reuse it.", "pesticide|insecticide|weedicide"],
      ["Fertiliser bag", "blue", "Empty and clean.", "fertilizer|manure bag"],
      ["Bird nest material", "green"],
    ],
  },

  {
    group: "Festival & events",
    rows: [
      ["Rangoli powder", "green", "Natural powders compost; synthetic colours do not.", "kolam|rangoli"],
      ["Diya (clay)", "red", "Inert terracotta. Reuse it next year.", "lamp|diya|earthen lamp"],
      ["Idol (clay)", "green", "Unpainted clay only.", "idol|vinayagar|ganesha"],
      ["Idol (plaster)", "red", "Plaster of Paris does not break down.", "pop idol"],
      ["Balloon", "red", "", "balloons"],
      ["Streamers", "red", "", "paper streamer|decoration"],
      ["Bunting (cloth)", "red", "Store it flat and reuse it.", "bunting|flags"],
      ["Fairy lights", "black", "", "string lights|serial lights"],
      ["Firecracker residue", "red", "Soak it in water before disposal.", "crackers|fireworks"],
      ["Thermocol decoration", "red", "", "decor|prop"],
      ["Paper plate (event)", "red"],
      ["Event badge", "blue", "Card badges can be returned and reused.", "badge|name tag|lanyard"],
      ["Lanyard", "red", "", "neck strap"],
      ["Conference kit bag", "red", "Decline it if you do not need it.", "delegate bag|kit"],
      ["Printed agenda", "blue", "Use a QR code instead next time.", "programme|agenda"],
      ["Certificate", "blue", "Digital certificates avoid this entirely.", "award certificate"],
      ["Trophy", "black", "", "memento|shield"],
      ["Bouquet wrapping", "red", "", "cellophane|bouquet"],
    ],
  },

  {
    group: "Cleaning & maintenance",
    rows: [
      ["Room sweepings", "red", "", "dust|sweeping|floor dust"],
      ["Vacuum cleaner dust", "red", "", "vacuum bag"],
      ["Broom", "green", "Natural bristle brooms compost; plastic ones do not.", "jhadu|broomstick"],
      ["Scrubber", "red", "", "scouring pad|sponge"],
      ["Steel wool", "blue", "", "scrubber steel"],
      ["Cleaning chemical bottle", "blue", "Rinse thoroughly. Residue-bearing bottles go to yellow.", "phenyl bottle|harpic|cleaner"],
      ["Bleach", "yellow", "", "hypochlorite|bleaching powder"],
      ["Drain cleaner", "yellow", "", "acid cleaner"],
      ["Disinfectant", "yellow", "", "phenyl|dettol"],
      ["Air freshener", "yellow", "Pressurised canister.", "room freshener"],
      ["Mosquito repellent", "yellow", "", "coil|liquidator|all out"],
      ["Rat poison", "yellow", "", "rodenticide|poison"],
      ["Paint", "yellow", "", "emulsion|enamel|primer"],
      ["Paint brush", "red", "", "brush"],
      ["Paint thinner", "yellow", "", "thinner|turpentine"],
      ["Adhesive tube", "yellow", "", "araldite|epoxy|sealant"],
      ["Silicone sealant", "yellow", "", "sealant"],
      ["Grease", "yellow", "", "lubricant|grease"],
      ["Sandpaper", "red", "", "emery paper"],
      ["Nails and screws", "blue", "Scrap metal.", "nail|screw|bolt|nut"],
      ["Hinge and fittings", "blue", "", "hinge|latch|handle"],
      ["Padlock", "blue", "", "lock|key"],
      ["PVC pipe", "red", "", "pipe|plumbing pipe"],
      ["Tap or faucet", "blue", "Brass and steel are valuable scrap.", "tap|faucet|valve"],
      ["Wash basin", "black", "Ceramic sanitaryware — bulky stream.", "sink|basin|toilet"],
    ],
  },

  {
    group: "Construction & renovation",
    rows: [
      ["Construction debris", "black", "Never mixed with household waste. Arrange separate lifting.", "rubble|malba|debris|renovation waste"],
      ["Broken tiles", "black", "", "tile|ceramic tile"],
      ["Cement bag", "red", "", "cement|sack"],
      ["Concrete rubble", "black", "", "concrete|brick"],
      ["Brick", "black", "Whole bricks are worth reusing.", "bricks"],
      ["Sand", "black", "", "m sand|river sand"],
      ["Plaster of Paris", "black", "", "pop|gypsum"],
      ["Glass wool", "black", "Irritant — bag it before handling.", "insulation|rockwool"],
      ["Asbestos sheet", "yellow", "Hazardous. Do not break or handle it yourself — report it.", "asbestos|roofing sheet"],
      ["Wooden door", "black", "", "door|window frame"],
      ["Metal grill", "blue", "Scrap metal.", "grill|railing"],
      ["Electrical conduit", "red", "", "conduit|casing"],
      ["Wall putty", "black", "", "putty"],
      ["Marble offcut", "black", "", "granite|stone"],
    ],
  },

  {
    group: "Sports & other",
    rows: [
      ["Tennis ball", "red", "", "ball|cricket ball"],
      ["Shuttlecock", "green", "Feather shuttles compost; plastic ones do not.", "shuttle|badminton"],
      ["Racket", "black", "Restring it before discarding.", "badminton racket|tennis racket"],
      ["Yoga mat", "red", "", "exercise mat"],
      ["Gym gloves", "red"],
      ["Sports tape", "red"],
      ["Musical instrument string", "blue", "Metal.", "guitar string"],
      ["Toy (plastic)", "blue", "Working toys belong on the swap shelf.", "toys|doll|blocks"],
      ["Soft toy", "red", "", "stuffed toy|teddy"],
      ["Board game", "blue", "Donate if complete.", "game|puzzle"],
      ["Playing cards", "blue"],
      ["Ceramic mug", "red", "Broken crockery — wrap it before disposal.", "cup|crockery|plate|broken mug"],
      ["Porcelain plate", "red", "", "china|dinner plate"],
      ["Cutlery (steel)", "blue", "", "spoon steel|fork steel"],
      ["Water filter cartridge", "black", "", "filter cartridge|candle filter"],
      ["Shoe polish tin", "red"],
      ["Key chain", "red"],
      ["Spectacle case", "red"],
      ["Wallet", "red", "", "purse"],
      ["Photo frame", "red", "Glass and mixed material.", "frame"],
      ["Candle", "red", "", "wax candle"],
      ["Incense stick ash", "green", "", "agarbatti|incense|ash"],
      ["Puja waste", "green", "Flowers and ash compost; foil and plastic do not.", "prasadam|offering"],
      ["Cigarette packet", "red", "", "cigarette box"],
      ["Lighter", "red", "Make sure it is empty.", "gas lighter"],
      ["Pen refill", "red", "", "refill|ink refill"],
      ["Dustpan", "red"],
      ["Plastic chair (broken)", "blue", "Rigid plastic is recoverable.", "broken chair"],
    ],
  },

  {
    group: "Hostel & mess",
    rows: [
      ["Mess tray", "blue", "Only when it is beyond use.", "tray|thali"],
      ["Mess plate waste", "green", "Scrape at the marked station so the wet line stays clean.", "plate waste|scrape"],
      ["Water purifier candle", "black", "", "filter candle"],
      ["Bucket handle", "blue"],
      ["Mug (plastic)", "blue"],
      ["Bed bug spray", "yellow", "", "insect spray"],
      ["Hostel notice paper", "blue"],
      ["Laundry bag", "red"],
      ["Detergent powder packet", "red", "", "washing powder"],
      ["Clothes peg", "red", "", "clip|cloth clip"],
      ["Iron box cover", "red"],
      ["Room key tag", "red"],
      ["Study chair cushion", "red"],
      ["Mosquito bat", "black", "Contains a battery.", "racket bat|mosquito racket"],
      ["Table fan blade", "black"],
      ["Instant coffee jar", "blue", "Rinse.", "nescafe jar|coffee jar"],
      ["Protein powder tub", "blue", "", "supplement tub"],
      ["Energy drink can", "blue", "", "red bull|energy can"],
      ["Disposable glass", "red", "", "plastic glass|paper glass"],
      ["Food delivery bag", "red", "", "swiggy bag|zomato bag"],
      ["Aluminium meal tray", "blue", "Rinse.", "foil tray|meal tray"],
      ["Cup noodles container", "red", "", "cup noodles"],
      ["Sauce bottle", "blue", "Rinse.", "ketchup bottle"],
      ["Jam jar", "blue"],
      ["Honey bottle", "blue"],
    ],
  },

  {
    group: "Office & admin",
    rows: [
      ["Shredded paper", "blue", "Shredding does not disqualify paper; contaminating it does.", "shredding|shredded"],
      ["Confidential document", "blue", "Secure shredding first, then the paper stream.", "confidential|personnel file"],
      ["Box file", "blue"],
      ["Lever arch file", "blue", "Remove the metal mechanism.", "arch file"],
      ["Desk organiser", "blue"],
      ["Stamp pad", "red", "", "ink pad|rubber stamp"],
      ["Punching machine", "blue", "Scrap metal.", "hole punch|puncher"],
      ["Stapler", "blue", "", "stapler machine"],
      ["Notice board pin", "blue", "", "drawing pin|push pin"],
      ["Whiteboard duster", "red", "", "board duster"],
      ["Projector", "black", "", "beamer|lcd projector"],
      ["Projector lamp", "black", "Contains mercury.", "projector bulb"],
      ["Telephone", "black", "", "landline|intercom"],
      ["Water dispenser", "black", "", "dispenser"],
      ["Office carpet tile", "black"],
      ["Name plate", "red"],
      ["Diary cover", "red"],
      ["Plastic sleeve", "red", "", "sheet protector"],
      ["Binder spine", "red"],
      ["Packing peanuts", "red", "", "loose fill"],
    ],
  },

  {
    group: "Miscellaneous",
    rows: [
      ["Unknown item", "red", "If it is not hazardous or electronic, red is the safe choice. Then tell us so we can add it.", "not sure|unsure|dont know|other"],
      ["Mixed waste", "red", "Sorting later almost never happens. Separate it now if you can.", "mixed|unsegregated"],
      ["Wet wrapper", "red", "The most common mistake on campus. Wet does not mean biodegradable.", "soaked wrapper|oily wrapper|greasy wrapper"],
      ["Oily paper", "red", "", "greasy paper|oil stained"],
      ["Soiled cardboard", "red", "", "wet cardboard|stained box"],
      ["Broken glass", "red", "Wrap it in newspaper and mark it ‘broken glass’ for the person who empties the bin.", "glass|broken bottle|shard"],
      ["Ceramic", "red", "", "pottery|earthenware"],
      ["Rubber", "red", "", "rubber sheet|rubber piece"],
      ["Leather", "red", "", "leather scrap"],
      ["Sponge", "red"],
      ["Velcro", "red"],
      ["Zip fastener", "red"],
      ["Magnet", "black", "", "fridge magnet"],
      ["Coin", "blue", "Metal, though you may prefer to keep it.", "coins"],
      ["Sandbag", "red"],
      ["Tarpaulin", "red", "", "tarp|plastic sheet"],
      ["Sacking", "blue", "", "hessian"],
      ["Bin liner", "red", "", "garbage bag|trash bag"],
      ["Compostable bin liner", "green", "Only certified compostable liners.", "compostable bag"],
      ["Face shield", "red"],
      ["Disposable apron", "red"],
      ["Shoe cover", "red"],
      ["Hair net", "red"],
      ["Chalk", "green", "Gypsum is inert; small quantities are fine in the wet stream.", "chalk piece"],
      ["Chalk dust", "red"],
      ["Ash", "green", "Wood and incense ash only. Coal ash goes to red.", "wood ash"],
      ["Coal ash", "red"],
      ["Charcoal", "green", "", "coal|barbecue coal"],
      ["Pet waste", "red", "Bag it.", "dog waste|cat litter"],
      ["Aquarium water", "green", "", "fish tank"],
      ["Wax paper", "red"],
      ["Foam sheet", "red"],
      ["Shrink wrap", "red"],
      ["Anti-static bag", "red"],
      ["Desiccant pack", "red"],
      ["Expired cosmetics", "yellow", "", "old makeup"],
      ["Expired paint", "yellow"],
      ["Expired sunscreen", "yellow"],
      ["Used mask (medical)", "red", "", "surgical mask used"],
      ["Sharps container", "yellow", "", "sharps box"],
      ["X-ray film", "yellow", "Contains recoverable silver — hand it over.", "xray|radiograph"],
      ["Photographic chemicals", "yellow", "", "developer|fixer"],
    ],
  },
];
